#!/bin/csh -f

alias ur_setup 'eval `/home/npk/.ureka/ur_setup -csh \!*`'
alias ur_forget 'eval `/home/npk/.ureka/ur_forget -csh \!*`'


setenv MOSPATH /scr2/mosfire/DRP/mosfire
setenv MOSPATH /home/npk/mdrp/
setenv PYTHONPATH ${PYTHONPATH}:${MOSPATH}

if (! -d $MOSPATH) then
    echo "Path '$MOSPATH' does not exist. Modify $0"
    echo "and change MOSPATH to the DRP directory."
    exit 1
endif

ur_setup

if ($#argv == 0) then
        echo "Starting MOSFIRE Python"
        ipython --pylab --colors Linux
else
    switch ( $argv[1] )
        case "libs":
            python -c "import sys; print sys.path"
            breaksw

        case "db":
            python ${MOSPATH}/apps/db.py $*
            breaksw

        case "handle":
            python ${MOSPATH}/apps/handle.py $*
            breaksw

        case "what":
            python ${MOSPATH}/apps/what.py $*
            breaksw

        default
            python $*
            breaksw
    endsw
endif

onintr -

    
