#!/bin/csh -f

#
# Mospy template for mac install
# 

source /usr/stsci/envconfig.mac/cshrc
iraf

setenv MOSPATH $HOME/mosfire/DRP
setenv PYTHONPATH ${PYTHONPATH}:${MOSPATH}
setenv PYRAF_NO_DISPLAY TRUE

if ($#argv == 0) then
	echo "Starting MOSFIRE Python"
	\ipython --pylab 
else
	switch ( $argv[1] )
		case "libs":
			python -c "import sys; print sys.path"
			breaksw
		case "what":
			python ${MOSPATH}/apps/what.py $*
			breaksw
        case "audit":
            python ${MOSPATH}/apps/audit.py $*
            breaksw
        case "db":
            python ${MOSPATH}/apps/db.py $*
            breaksw
		default:
			python $*
			breaksw
	endsw
endif

onintr -
